---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    name: test-service
spec:
  type: NodePort
  ports:
    - port: 8282
      nodePort: 32222
      name: http
  selector:
    name: test-app
